name: Experimental Github Action
description: Experiemental Github Action from engines.dev
author: engines.dev

branding:
  icon: heart
  color: red

inputs:
  pr_sha:
    description: Commit hash
    required: false
    default: ${{ github.event.pull_request.head.sha }}

  file_path:
    description: Path to any file
    required: true
    default: 'README.md'

  test_run_cmd:
    description: Command to run tests
    required: true
    default: 'npm run ci-test'

outputs:
  file_path:
    description: Path to the file that was edited

  first_line:
    description: First line to the specified file

runs:
  using: 'composite'
  steps:
    - name: Process Pull Request
      uses: ./dist/index.js
      with:
        pr_sha: ${{ github.event.pull_request.head.sha }}
        file_path: $${{ inputs.file_path }}
        test_run_cmd: $${{ inputs.test_run_cmd }}

    - name: Create or Update Pull Request
      uses: gr2m/create-or-update-pull-request-action@v1
      with:
        branch: ${{ github.event.pull_request.head.ref }}
        commit-message:
          'Updated ${{ steps.test-action.outputs.file_path }} with `${{
          steps.test-action.outputs.edit }}`'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
