name: Experimental Github Action
description: Experiemental Github Action from engines.dev
author: engines.dev

branding:
  icon: heart
  color: red

inputs:
  pr_sha:
    description: Commit hash
    required: false
    default: ${{ github.event.pull_request.head.sha }}

  file_path:
    description: Path to any file
    required: true
    default: 'README.md'

  test_run_cmd:
    description: Command to run tests
    required: true
    default: 'npm run ci-test'

outputs:
  first_line:
    description: First line to the specified file

  pr_updated:
    description: Whether the PR was successfully updated

runs:
  using: node20
  main: dist/index.js
