name: Experimental Github Action
description: Experiemental Github Action from engines.dev
author: engines.dev

branding:
  icon: heart
  color: red

inputs:
  milliseconds:
    description: Input that defines the number of milliseconds to wait
    required: true
    default: '200'

outputs:
  time:
    description: Output is the current time

runs:
  using: node20
  main: dist/index.js
